In [1]:
import numpy as np

reshape

In [2]:
test_matrix = [[1,2,3,4],[5,6,7,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
test = np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
test.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [18]:
np.array(test_matrix).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.array(test_matrix).reshape(2,-1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.array(test_matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

flar or flatten()

In [22]:
test_matrix = [[[1,2,3,4],[1,2,5,8], [1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])