In [1]:
import numpy as np

In [3]:
test_example = np.array([[1,2,3], [4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
test_example[0][0]

1

slicing

In [6]:
test_example = np.array([
    [1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]
], int)

test_example [:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [7]:
test_example[:,1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])